name: tests

on:
  push:
    branches-ignore: [ main, dev ]
  pull_request:
    branches-ignore: [ main, dev ]

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  build-linter-utests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          components: rustfmt, clippy

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.10
      - uses: sergeysova/jq-action@v2
        id: sccache_release
        with:
          cmd: 'curl --silent "https://api.github.com/repos/Qovery/sccache-bin/releases/latest" | jq .tag_name'
          multiline: false
      - name: build-linter-utests
        run: |
          echo "########## LINTER ##########"
          cargo fmt --all -- --check --color=always  || (echo "Use cargo fmt to format your code"; exit 1)
          cargo clippy --all --all-features --lib -- -D warnings || (echo "Solve your clippy warnings to continue"; exit 1)
          export PATH=$GITHUB_WORKSPACE/bin:$PATH
          export RUSTC_WRAPPER=$GITHUB_WORKSPACE/bin/sccache
          export TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache
          export SCCACHE_REDIS=${{ secrets.SCCACHE_REDIS }}
          mkdir -p $GITHUB_WORKSPACE/bin $HOME/.terraform.d/plugin-cache
          echo "########## START BUILD ##########"
          cargo build --all-features --tests
          echo "########## START UNIT TESTS ##########"
          cargo test
